language: node_js
node_js:
- 0.10.25
install:
- npm install -g gulp
- npm install -g bower
- npm install
- bower install
script:
- gulp test
- gulp build
sudo: false
after_success:
- gulp coveralls
deploy:
  provider: npm
  email: atran@appirio.com
  api_key:
    secure: JY+SJ4U46UTHbAnh1m8k3TLQAs2onO8VHvRY51m988znvnI2t3bsm0uq7aYYzCpThHWBujUGJZp6Z/glLdDBSW3BNu5N99K1IJhGNy25lNrlYisN2JaGDkuINQGSEEEmz8Mge5smvK4/Yy49H+re6FSSOstspJyDz68Jd2n7wgbfjqreeid5Rg+IWSRAUZnWxBb1+I4NhGcGQ25CLiogLlXCcSWfciGGnoRboFliTnhP20XxQrFmaTJkILNQvdiNABsjljQpnwu5dY86w3Ndhke2ln2WJ2YXfOO8wV7yRBUWbphDLell7qsYvAT05NKSPBbLszBc5QiP5KykqQ7XZNuQ21427yDQFQdwK0HIKr0MgIymsgQmmdLJRVLX3fwwcCHp5zFfw+vhHZaaO9TOy9pHTUn91foM0xtq+mvIFZMJblW1mI2xknBC0dVvhRV0cNE7xAcsgDy8FEjAqv8JNQjjfRQXUutSlmIVZbLMBa/O8kO16h1DedZt2XLEp7JTxZNSJaLf9wEDFU+CQgfXORXRCMWjBdF6+NjhXF3fQwke5V3v5+bYur7hcw5JdMbioBvrxp81PT1n8SSbbW3EjyNWaG7MyTzQ9EIDmDU1fNDI61lO1Fo247qH/2omBbRYE2Ui8vDx1U4ge7aCrp9ozSH29gvNAFC91Gw9vOF8Q2w=
  on:
    tags: true
