deploy:
  provider: npm
  email: fake-address_123@aol.com
  api_key:
    secure: NRs66vmk6AvkEGj0kMPsS5FImmHLtrWv+WXLCiRa6Jaslfn4nZYFHyeX3BTVMlWgYqpB6vY6RozbwZ2eRdHQfMVdn2BKcMIcY1dQ/bKpX5P/xwvZQzHvZGJx3HxA7RyTytHsyjX5YHe8jm+HrCW4kzb7UY2Edu6NVdrsHx0R3dV21aQZsuuwcKhbJaWUfQYZw4j+Z08Y8RJOsyfwS3J3sYbhEyd1QsOL8b5CaYpfR84ivGyewZeAdFyoZdoBagrdPtLhcxzlosVgQZo8SW6T4qCj+uHrg3yrMTQRrAGMXRzf9ay8YKldEEIgFW8GRKwRzLFTVLmiS0B2zIW/da7QsIr36K/aBKCy8wEmC8lBAk69dQVHMjvQ82FR8AhFz8gXIdQ8MxzqU5FsSxlNjBUGLrNvrkfmUU127SeTt9/E3uONveueZl9cQ+8KHj7MB6GKMwHcxK45rfm755ngfMlDT9VmAiuvkxDR1wnVvIkPHYeLXZaRE6uZaiEb9QWWTDef0kOBmu5BY8HfkUbfTSjkq5GlovewlpIYCesMRdUau6JtGj0C40+PYH4b4feTMySN2VHNBZhjsaRebaWg90mkYSTFzzGoPfjJV5fB31p4/41Lo8aWv2D+vk+28909MJ0+M75rBnlizQEzZAEjFd08nqSGAO5MjKCz69eFs+eFruA=
  on:
    tags: true
