language: node_js
node_js:
- 0.10.25
before_install:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
install:
- npm install -g npm
- npm install -g gulp
- npm install -g bower
- npm install
- bower install
script:
- gulp clean
- gulp preprocessors
- gulp test
- gulp useref
- gulp copy-files
- gulp remove-code
- gulp optimize-build
- gulp finger-print
- gulp finger-print-replace
sudo: false
after_success:
- gulp coveralls
