language: node_js
node_js:
- 0.10.25
install:
- npm install -g gulp
- npm install -g bower
- npm install
- bower install
script:
- gulp test
- gulp clean
- gulp preprocessors
- gulp useref
- gulp copy-files
- gulp remove-code
- gulp e2e-test
- gulp optimize-build
- gulp finger-print
- gulp finger-print-replace
sudo: false
after_success:
- gulp coveralls
