language: node_js
node_js:
- 0.10.25
install:
- npm install -g npm
- npm install -g gulp
- npm install -g bower
- npm install
- bower install
script:
- gulp test
- gulp clean
- gulp preprocessors
- gulp useref
- gulp copy-files
- gulp remove-code
- gulp e2e-test
- gulp optimize-build
- gulp finger-print
- gulp finger-print-replace
sudo: false
after_success:
- gulp coveralls
deploy:
  provider: npm
  email:
    secure: kbanIc+fczA0SlR+PJcDxx46Rv7Le35e9TB/gHc/a3Vwu1RNGodlNo62vBRw+PuqS3ue/1Yqkef/Z0CF2Wg005WcM4h28dcDl1HMVtkbzwJFPEjrPPlv9pz/pmf4gZGC9+l2TPGelgLUDoB8VUPfMduqmlexnPtYbCK7UDTaias40neDT/x+Kv3YmYQYfDtlaQHXCU86A2BhwZQOwATNSTmbif8ZIt16Z67YB2yXIa0B8smypDmPiey4Lh6SBv9gNuwsb4SrESZUhzW3FD5GuQyxHLeBqmK6Bto3T/4U1RcqJL/JlktFVc3dLaQFo65pRfpyioIgOWDQZ0h4JuwG7k8l1/WmDbo1DFZdb9cH+fijIIDjaDZIIJwi4JLfL6JiRvdBr6rUMMR7wgUq6WJikykN2zTdBKUexFhYB7w2q64wQeuJ5j21u62QdsYmF63qUxVRWvFKXH3Q/QKhHWb5Bm5CV/h4gAZ0US6+JWBH7pzf7jjwVKvPpuWPDpAiLy5ZQIxXJoxRjd52Ec+HUbqAAJz/1XLAj37LPOTLWOa0jP5yV8ONFw2SefFztLfLjfgZrAArtX8ocovHQuLMvwDFf8eb+DJ/QBntZRqMomn76nRmFoaEBbYjLI+9zHxjXBLq4BU88/mpN2aRytsABRrHME2Em+J2vClBqlZRCrPNHsY=
  on:
    tags: true
  api_key:
    secure: mcYQ/vOkfqdHeZOWQ07+38irk4DVqULv+YHzZwfmWqJZ7RbWlh0k8sSYQwbeGYkZXSTNmU31HHQs0Ryhgp2QWATpbWSzDl60Oeoro7THBUd8ixzD/NUcTTVIwHw6FaRgt9IooCf6huaNq7v5AvcSyTonD94iO0v1x3AJTjJ1ETIKDwZI+ZyftSvofp41ipUEEmbCM10gaXkH5lvsyzyCzqx9+x8QCBtaFx4HLE3NjVNzBsBmr0hrwtkpAdNP21ZStJT1xydrdDYk1I5NdjfQinvmIg5LgiVzey1TET59Iw4zn63TkirjMVW+HddZmXrg/jpt9jbeGmkmnZVNUP5U2b6oa9BSj85Yu+ec79MPFyfeYKq9W8T6yzc8j9a640pKML7GYmB0YA+McMPbsAg8vIDRaoxHaEtpSdZl+3rY5lfRV7KLO90i5CSNh/eV92akiUW+h6qwa3ckt+tFYnHy1UNoHOtrvwvKuLAppyc2oBElhK5+ZhHpi+2eAH9OqKjoluHvJ8suElqQuyREsutqdCl8DDb9NzhClY+obvKMIoqwYNdB6F0LLxQlIxju0fzM7EtpkknNa5kysR5A1cUQ6PBFA1dU+SNaXJhnbBeusDs7nUUvm7a1DQDOftliqo8t5Z7lJYNZfID9jy2RAf9R8bAnXPE6v03w7Aj8xgDUYDA=
